### ISSUE TITLE
Interrupt REPL

### ISSUE THREAD

**Issue by seyaryuki** [erietz/vim-terminator#11]
Hi,

thanks for writing this great plugin. 

Is there a way to interrupt something running in the REPL?

I tried `:TerminatorStopRun` but it doesn't seem to work with the REPL.
I also tried sending some interrupt sequence via `:TerminatorSendToTerminal` but I didn't manage to make it work.

**Comment by erietz** [comment]
The command `:TerminatorStopRun` stops the process if it is being run in the output buffer. If I want to kill the job in the terminal I usually just change windows over to the REPL and hit ctrl-c if I need to stop it. Your approach with `:TerminatorSendToTerminal` seems like a good one. I just tried to send a few sequences like ctrl-c and ctrl-d via the `:TerminatorSendToTerminal` command to the REPL and haven't figured anything out yet.
